server:
  port: 8080
girl:
  cupSize: B
  age: 18
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true